#######################
# Theme Customization #
#######################

title: Jim Chen                             # used in <title> tag & site header
author: Jim Chen                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  Hello 911 emergency, there's a handsome guy in my house!
  Oh wait a second, cancel that. It's only me.
slogan: Showtime!                           # used in site header, beside title
avatar: /i/avatar.png                       # used as portrait in site header
banner: /i/mountains.svg                    # used as background in site header
url: http://solana.ryanlue.com              # used by plugins to generate feed.xml and sitemap.xml
baseurl: ''                                 # prepended to all absolute filepaths
repo: https://github.com/jimchenhub/jimchenhub.github.io # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Posts
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Projects
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/jimchenhub/
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  # - name: Contact
  #   scheme: mailto          # these keys enable email obfuscation.
  #   handle: jimchen@      # you know, to protect you from bots. (handle and domain
  #   domain: qq.com          # are separated in case bots crawl GitHub repos, too.)
  #   icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: Transferable UAV
    teaser: A new pipeline of training a monocular UAV to fly a collision-free trajectory along the dense forest trail
    url: https://sites.google.com/view/forest-trail-dataset
    role: Author
    category: UAV, Transfer Learning, DAN
  - title: Rich Details Monocular Depth Prediction
    teaser: Monocular depth prediction with relative supervision to preserve better object details
    url: https://sites.google.com/view/rich-detail-depth
    role: Author
    category: Depth Prediction, Relative Supervision
  - title: VALID
    teaser: Virtual AeriaL Image Dataset
    url: https://sites.google.com/view/valid-dataset
    role: Author
    category: Aerial Image, Dataset
  - title: Smart Car
    teaser: Avoid obstacles automatically using image processing and machine learning
    url: https://github.com/jimchenhub/Smart-Car
    role: Creator
    category: OpenCV, CNN, Raspberry PI 

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
